### ISSUE TITLE
Fujitsu toolchain TODO list for EB v4.4.0

### ISSUE THREAD

**Issue by migueldiascosta** [easybuilders/easybuild#701]
#### Framework
- [x] toolchain definitions: https://github.com/easybuilders/easybuild-framework/pull/3677
  - [x] hierarchy: FCC, ffmpi, Fujitsu (even though MPI and SSL are provided by the `lang` module)
  - [x] make sure `fcc` is always called with `-Nclang`, even when `CFLAGS` is not used (e.g. `_ctypes/libffi` configure script in `Python2`)
  - [x] `-Kfp_precise` doesn't work in clang mode, closest we can get seems to be `-Knoeval,nofast_matmul,nofp_contract,nofp_relaxed,noilfunc` (and at least the tests that require precise in GMP do pass with these flags)
  - [x] `-KNOSVE` also doesn't work in clang mode (use `-Knosimd` instead)
  - [x] `-Kfast` is actually `-O3` plus a bunch of other stuff, so to play it safe keep default level at `-O2` and leave `-Kfast` to `opt` and specific easyblocks
  - [x] including `arm_sve.h` fails in clang mode when including the top level include dir of the `lang` module (in `clang` mode it should be the one in e.g. `$EBROOTLANG/clang-comp/lib64/clang/7.1.0/include`, but there is no need to add it), skip it when adding include flags for dependency prefixes
  - [x] test with `RPATH`
  - [x] make sure top level `lib64` dir of `lang` module is found and added to rpath by wrapper
    - [x] use LDFLAGS instead of LIBRARY_PATH, so that it is added to the buildenv module: https://github.com/easybuilders/easybuild-framework/pull/3704
  - [x] add `required` keyword argument (introduced in https://github.com/easybuilders/easybuild-framework/pull/3555) to overriden `_get_software_root`: https://github.com/easybuilders/easybuild-framework/pull/3704
- [x] w.r.t. https://github.com/easybuilders/easybuild-framework/pull/3677/commits/2138971a1c37146a240302e4f2177f1c0e89d9be, we need a better solution for passing `-Nclang`: it was moved to CC and CXX in compiler toolchain definition because some configure scripts (e.g. `_ctypes/libffi`) don't use C[XX]FLAGS when detecting the compiler, but on the other hand some scripts try to find an executable named `fcc -Nclang` and fail, including easybuild itself: ```WARNING Could not find command 'fcc -Nclang' (...) DEBUG Not installing RPATH wrapper for non-existing command 'fcc -Nclang'```, so this is not right; moved back to C[XX]FLAGS in https://github.com/easybuilders/easybuild-framework/pull/3713
- [x] w.r.t. https://github.com/easybuilders/easybuild-framework/pull/3704, we probably need to set both LIBRARY_PATH and LDFLAGS, some builds don't use LDFLAGS so the RPATH wrapper misses it (without RPATH it's not a problem because the compiler always looks at this path for dynamic libraries); done in https://github.com/easybuilders/easybuild-framework/pull/3714
  - [x] only add libdir to LIBRARY_PATH if it's not already there: ~~https://github.com/easybuilders/easybuild-framework/pull/3717
 
#### Easyblocks
- [x] update `fftw` easyblock: https://github.com/easybuilders/easybuild-easyblocks/pull/2425

#### Easyconfigs
- [x] don't use `--try-toolchain --copy-ec` to generate easyconfigs to contribute back, use cp/mv/sed scripts instead
- [x] FCC: https://github.com/easybuilders/easybuild-easyconfigs/pull/12863
  - [x] version pinning
  - [x] binutils `osdep`
  - [x] use the compiler version, `FCC-4.5.0`, instead of `FCC-21.05` (currently the modules available are `lang/tcsds-1.2.29` with Fujitsu Compiler `4.3.1`, `lang/tcsds-1.2.30a` with Fujitsu Compiler `4.4.0a` and `lang/tcsds-1.2.31` with Fujitsu Compiler `4.5.0`, so it does seem to be one compiler version per module version): done in https://github.com/easybuilders/easybuild-easyconfigs/pull/12995
- [x] binutils and dependencies: https://github.com/easybuilders/easybuild-easyconfigs/pull/12996
  - [x] configure script seems to be confused about the presence of limits.h and fcntl.h when using the Fujitsu compiler, fixed with `prebuildopts = 'export CFLAGS="-DHAVE_LIMITS_H -DHAVE_FCNTL_H $CFLAGS" && '`
  - [x] M4: building was hitting this, https://bugs.llvm.org/show_bug.cgi?id=16404
    - [x] fixed by adding `--rtlib=compiler-rt` to $LDFLAGS (this may be necessary in other places...)
- [x] Perl and dependencies: https://github.com/easybuilders/easybuild-easyconfigs/pull/12997
  - [x] Perl extension `XML-Bare` has hardcoded `CC=gcc`, `SetInterval` tries to use `clang++`, used `exts_default_options = {'buildopts': 'CC="$CC"'}` but may be worth addressing more generically in easyblock?
- [x] Autotools and dependencies: https://github.com/easybuilders/easybuild-easyconfigs/pull/12998
- [x] FFTW: https://github.com/easybuilders/easybuild-easyconfigs/pull/12999
- [x] ffmpi + OSU-Micro-Benchmarks: https://github.com/easybuilders/easybuild-easyconfigs/pull/13000
- [x] Full toolchain + HPL: https://github.com/easybuilders/easybuild-easyconfigs/pull/13001
  - [x] MPI doesn't seem to be supported in Fujitsu's FFTW yet, so it's disabled in the easyconfig and moving it to `FCC` instead of `ffmpi` to make that clear
  - [x] decide name (and versionsuffix?) of FFTW module (https://github.com/easybuilders/easybuild-easyconfigs/pull/12863#discussion_r639503172): done in https://github.com/easybuilders/easybuild-framework/pull/3712

**Comment by boegel** [comment]
@migueldiascosta 

> w.r.t. easybuilders/easybuild-framework@2138971, we need a better solution for passing -Nclang: it was moved to CC and CXX in compiler toolchain definition because some configure scripts (e.g. _ctypes/libffi) don't use C[XX]FLAGS when detecting the compiler, but on the other hand some scripts try to find an executable named fcc -Nclang and fail, including easybuild itself: WARNING Could not find command 'fcc -Nclang' (...) DEBUG Not installing RPATH wrapper for non-existing command 'fcc -Nclang', so this is not right
> * one option would be to enforce RPATH and make sure -Nclang is set in the RPATH wrapper (?)

We can enhance framework to strip off flags from the `$CXX` value before it tries to locate the command, but even then you may run into surprises in some places. The best way to fix may be to ensure that `$CXXFLAGS` is picked up consistently, but that seems painful?
I'm not sure that abusing the RPATH wrappers makes sense. Perhaps we need another compiler wrapper script that can be used to inject specific flags (and then have the RPATH wrapper call that wrapper rather than the actual compiler)?

> w.r.t. easybuilders/easybuild-framework#3704, we probably need to set both LIBRARY_PATH and LDFLAGS, some builds don't use LDFLAGS so the RPATH wrapper misses it (without RPATH it's not the problem because the compiler always looks at this path for dynamic libraries)

Same solution, a separate wrapper to inject what's needed?

**Comment by migueldiascosta** [comment]
split into what went into EB v4.4.0, this issue, and what's still open, https://github.com/easybuilders/easybuild/issues/704
