### ISSUE TITLE
Fujitsu toolchain TODO list for EB v4.4.1

### ISSUE THREAD

**Issue by migueldiascosta** [easybuilders/easybuild#704]
#### Framework
- [ ] HierarchicalMNS support: 
  - [ ] needs COMPILER_MODULE_NAME = ['FCC'] in toolchains/fujitsu.py
    - [ ] but also changes to the HierarchicalMNS itself, since there isn't an mpi module, it's included in FCC (but we can create a fake module to keep the same levels...)
    - [ ] also, `moduleclass` of FCC should be `compiler` instead of `toolchain`
- [ ] add `etc/fujitsu_external_modules_metadata.cfg`? (for now, it would be ```[lang/tcsds-1.2.31]\nname = lang\nversion = tcsds-1.2.31\nprefix = FJSVXTCLANGA```)
- [ ] `-SSL2*` and `-SCALAPACK` should be used only when linking but easybuilds prepends `-L` to `LDFLAGS` variables, so they are currently in compile flags (not a problem but generate warnings that pollute the logs) (https://github.com/easybuilders/easybuild-framework/issues/3700)
  - [ ] also, right now `-SSL2*` flags are being duplicated, probably being set by both `_set_blas_variables` and `_set_lapack_variables`, should be easy to fix
#### Easyblocks
- [ ] update `fortranpythonpackage` easyblock: https://github.com/easybuilders/easybuild-easyblocks/pull/2434
  - [ ] numpy 1.20.3 already has a 'fujitsu' fcompiler defined: https://github.com/numpy/numpy/pull/17792
- [ ] update `berkeleygw` easyblock: https://github.com/easybuilders/easybuild-easyblocks/pull/2428
  - [ ] check for fujitsu fftw in a different way (https://github.com/easybuilders/easybuild-easyblocks/pull/2428#discussion_r639502727)

#### Easyconfigs
- [ ] Python: PR upcoming
  - [x] Unzip Makefile has hardcoded `CC=cc`, needs CC="$CC" buildopt (added to all other UnZip easyconfigs in https://github.com/easybuilders/easybuild-easyconfigs/pull/12887)
  - [ ] downgraded `cryptography` extension in order to avoid `Rust` dependency, which will need to be patched to detect the compiler
- [ ] SciPy-bundle
- [ ] CMake: PR upcoming
  - [ ] linker flags and FindMPI patch, pass -Nclang via C[XX]FLAGS because CMake's bootstrap is stripping it from CC and CXX...
- [ ] Boost
- [ ] gearshifft
- [ ] ELPA
  - [ ] "The 'OPTIONAL' attribute must not be specified for the dummy argument 'success' of a procedure that has the procedure language binding specifier"
- [ ] BerkeleyGW: https://github.com/easybuilders/easybuild-easyconfigs/pull/12868
